import { describe, expect, it } from "vitest";

import fixtureJson from "./fixtures/python-random.json?raw";
import { PythonRandom } from "./pythonRandom";

interface FixtureCase {
  seed: string;
  mixedBits: Array<{ bits: number; value: string }>;
  getrandbits32AtStateBoundary: string[];
  random: number[];
  randrange2Pow63: string[];
  shuffle52: number[];
}

interface Fixture {
  generator: string;
  cases: FixtureCase[];
}

const fixture = JSON.parse(fixtureJson) as Fixture;

describe("PythonRandom CPython 3.11 compatibility", () => {
  it("uses a fixture generated by CPython 3.11", () => {
    expect(fixture.generator).toMatch(/^CPython 3\.11\./);
  });

  for (const testCase of fixture.cases) {
    describe(`seed ${testCase.seed}`, () => {
      it("matches mixed-width getrandbits calls", () => {
        const rng = new PythonRandom(testCase.seed);
        const actual = testCase.mixedBits.map(({ bits }) => rng.getrandbits(bits).toString());
        expect(actual).toEqual(testCase.mixedBits.map(({ value }) => value));
      });

      it("matches across the 624-word MT19937 state boundary", () => {
        const rng = new PythonRandom(testCase.seed);
        const values = Array.from({ length: 635 }, () => rng.getrandbits(32).toString());
        expect(values.slice(620)).toEqual(testCase.getrandbits32AtStateBoundary);
      });

      it("matches random() exactly", () => {
        const rng = new PythonRandom(testCase.seed);
        expect(testCase.random.map(() => rng.random())).toEqual(testCase.random);
      });

      it("matches randrange(2**63), including rejection sampling", () => {
        const rng = new PythonRandom(testCase.seed);
        const stop = 2n ** 63n;
        expect(testCase.randrange2Pow63.map(() => rng.randrange(stop).toString())).toEqual(
          testCase.randrange2Pow63,
        );
      });

      it("matches shuffle()", () => {
        const rng = new PythonRandom(testCase.seed);
        const values = Array.from({ length: 52 }, (_, index) => index);
        rng.shuffle(values);
        expect(values).toEqual(testCase.shuffle52);
      });
    });
  }

  it("accepts equivalent safe-number, bigint, and decimal-string seeds", () => {
    const sample = (rng: PythonRandom) => Array.from({ length: 20 }, () => rng.getrandbits(64));
    expect(sample(new PythonRandom(42))).toEqual(sample(new PythonRandom(42n)));
    expect(sample(new PythonRandom(42))).toEqual(sample(new PythonRandom("42")));
  });

  it("does not silently round an unsafe number seed", () => {
    expect(() => new PythonRandom(Number.MAX_SAFE_INTEGER + 1)).toThrow(/bigint/);
  });

  it("reproduces CPython's absolute-value handling for negative integer seeds", () => {
    const positive = new PythonRandom(1n);
    const negative = new PythonRandom(-1n);
    expect(Array.from({ length: 20 }, () => negative.getrandbits(64))).toEqual(
      Array.from({ length: 20 }, () => positive.getrandbits(64)),
    );
  });

  it("supports the general integer randrange form", () => {
    const rng = new PythonRandom(1234);
    for (let index = 0; index < 100; index += 1) {
      const value = rng.randrange(25n, -26n, -5n);
      expect(value <= 25n && value > -26n).toBe(true);
      expect((25n - value) % 5n).toBe(0n);
    }
  });

  it("validates impossible inputs instead of using an alternate random source", () => {
    const rng = new PythonRandom(0);
    expect(() => rng.getrandbits(-1)).toThrow(RangeError);
    expect(() => rng._randbelow(0)).toThrow(RangeError);
    expect(() => rng.randrange(0)).toThrow(RangeError);
    expect(() => rng.randrange(0, 10, 0)).toThrow(RangeError);
  });
});
